rvm:
  - 2.0.0-p353
  - 1.9.3
  - jruby

# whitelist
branches:
  only:
    - master
    - v1.3.x-bugfix

notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
