sudo: false

# Keep in sync with cucumber.gemspec's required_ruby_version
matrix:
  include:
    - rvm: ruby-head
      os: linux
    - rvm: ruby-head
      os: osx
    - rvm: 2.4.1
      os: linux
      # TravisCI OSX doesn't work with Ruby 2.4.1 yet (https://github.com/travis-ci/travis-ci/issues/7848)
    - rvm: 2.4.0
      os: osx
    - rvm: 2.3.4
      os: linux
    - rvm: 2.3.4
      os: osx
    - rvm: 2.2
      os: linux
    - rvm: 2.2
      os: osx
    - rvm: 2.1
      os: linux
    - rvm: 2.1
      os: osx
    - rvm: jruby-9.1.13.0
      os: linux
      env:
        # Travis by default also have "-Dcext.enabled=false" set in
        # JRUBY_OPTS, but JRuby 9 does not support C extensions at all
        # so it issues warning that will mess up the sterr checks.
        - JRUBY_OPTS="--server -Xcompile.invokedynamic=false"
        # Somehow a "ASCII-8BIT to UTF-8 conversion error" appears for
        # JRuby 9
        - LC_ALL=en_US.UTF-8
        - LANG=en_US.UTF-8
        - LANGUAGE=en_US.UTF-8
    - rvm: jruby-9.1.13.0
      os: osx
      env:
        # Travis by default also have "-Dcext.enabled=false" set in
        # JRUBY_OPTS, but JRuby 9 does not support C extensions at all
        # so it issues warning that will mess up the sterr checks.
        - JRUBY_OPTS="--server -Xcompile.invokedynamic=false"
        # Somehow a "ASCII-8BIT to UTF-8 conversion error" appears for
        # JRuby 9
        - LC_ALL=en_US.UTF-8
        - LANG=en_US.UTF-8
        - LANGUAGE=en_US.UTF-8
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

# whitelist
branches:
  only:
    - master
    - v1.3.x-bugfix
    - expanded_ci

before_install:
  - gem update --system
  - gem update bundler

notifications:
  webhooks:
    urls: # gitter
      - https://webhooks.gitter.im/e/dc010332f9d40fcc21c4
  slack: cucumberbdd:oQFVhzsx4R94KWmjlejAJYnM
