sudo: false

matrix:
  include:
    - rvm: 2.3.0
    - rvm: jruby-9.0.5.0
      env: 
        # Travis by default also have "-Dcext.enabled=false" set in
        # JRUBY_OPTS, but JRuby 9 does not support C extensions at all
        # so it issues warning that will mess up the sterr checks. 
        - JRUBY_OPTS="--server -Xcompile.invokedynamic=false"
        # Somehow a "ASCII-8BIT to UTF-8 conversion error" appears for 
        # JRuby 9
        - LANG=en_US.UTF-8

# whitelist
branches:
  only:
    - master
    - v1.3.x-bugfix

before_install:
  - gem update bundler

notifications:
  email:
    - cukes-devs@googlegroups.com
  webhooks:
    urls: # gitter
      - https://webhooks.gitter.im/e/dc010332f9d40fcc21c4
