sudo: false

matrix:
  include:
    - rvm: ruby-head
    - rvm: 2.4.1
    - rvm: 2.3.4
    - rvm: 2.2
    - rvm: 2.1
    - rvm: jruby-9.1.2.0
      env:
        # Travis by default also have "-Dcext.enabled=false" set in
        # JRUBY_OPTS, but JRuby 9 does not support C extensions at all
        # so it issues warning that will mess up the sterr checks.
        - JRUBY_OPTS="--server -Xcompile.invokedynamic=false"
        # Somehow a "ASCII-8BIT to UTF-8 conversion error" appears for
        # JRuby 9
        - LC_ALL=en_US.UTF-8
        - LANG=en_US.UTF-8
        - LANGUAGE=en_US.UTF-8
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

# whitelist
branches:
  only:
    - master
    - v1.3.x-bugfix

before_install:
  - gem update --system
  - gem update bundler

notifications:
  webhooks:
    urls: # gitter
      - https://webhooks.gitter.im/e/dc010332f9d40fcc21c4
